# fly.toml app configuration file generated for fso-lk-cicd-pokedex on 2023-08-21T13:39:05+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fso-lk-cicd-pokedex"
primary_region = "arn"

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.20.0"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
