name: Health check

on:
  schedule:
    - cron: '0,15,30,45 * * * *'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          url: ${{ vars.HEALTH_CHECK_URL }}
          max-attempts: 3
          retry-delay: 15s
