name: Hello Github actions

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello actions!"
      - name: Tell time
        run: date
      - name: Directory contents
        run: ls -l
