name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  check_for_skip:
    runs-on: ubuntu-20.04
    outputs:
      skip_deploy: ${{ steps.skip_check.outputs.skip_deploy }}
    steps:
      - uses: actions/checkout@v3
      - name: check commit messages for skip
        id: skip_check
        env:
          CONTAINS_SKIP: ${{ contains(join(github.event.commits.*.message), '#skip') }}
        run: echo "skip_deploy=$CONTAINS_SKIP" >> $GITHUB_OUTPUT
  simple_deployment_pipeline:
    needs: [check_for_skip]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - run: npm run build
      - run: npm run test
      - name: Run e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: Deploy to Render
        env:
          SKIP_DEPLOY: ${{ needs.check_for_skip.outputs.skip_deploy }}
        if: ${{ github.event_name == 'push' && env.SKIP_DEPLOY == 'false'}}
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
  tag_release:
    needs: [simple_deployment_pipeline, check_for_skip]
    if: ${{ github.event_name == 'push' && needs.check_for_skip.outputs.skip_deploy == 'false' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
