name: Testing stuff

on:
  push:
    branches:
      - pipeline-test

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: commit messages
        env:
          CONTAINS_SKIP: ${{ contains(join(github.event.commits.*.message), '#skip') }}
        run: echo "SKIP_DEPLOY=$CONTAINS_SKIP" >> $GITHUB_ENV
      - name: do something if not skip
        if: ${{ env.SKIP_DEPLOY == 'false' }}
        run: echo "let's deploy or something"
      - name: echo if skip or no skip
        run: echo "should skip ${{ env.SKIP_DEPLOY }}"
  another_job:
    needs: [a_test_job]
    runs-on: ubuntu-20.04
    if: ${{ env.SKIP_DEPLOY == 'true' }}
    steps:
      - name: conditionally do something
        run: echo "this job will skip"
